//! Renders the pattern library as `docs/PATTERN-CATALOGUE.md`.
//!
//! The catalogue is generated, never hand-edited: `tests/catalogue_test.rs`
//! regenerates it and fails if the committed file differs, so a pattern PR
//! that forgets to regenerate cannot merge. That matters more here than for a
//! typical generated doc — this one tells a reader what a security tool
//! detects, and a stale entry is a claim the scanner no longer honours.
//!
//! Built from [`PatternCategory`] directly rather than from `GradedRule`, so
//! that adding `example`/`counter_example` to the catalogue does not widen the
//! `rules --format json` key set that `tests/json_contract_test.rs` pins for
//! downstream consumers.

use crate::pattern::{PatternCategory, Severity};

/// Marker written into the file so a human who opens it knows not to edit it.
pub const GENERATED_MARKER: &str =
    "<!-- generated by `injection-scanner rules --format markdown` — do not edit by hand -->";

/// Characters that carry meaning but render as nothing.
///
/// Several encoding patterns match exactly these, so a code fence containing
/// one would look empty in the rendered doc. They are shown escaped alongside
/// the literal so the entry is readable.
fn has_invisible(text: &str) -> bool {
    text.chars().any(|c| {
        c.is_control() || matches!(c as u32, 0x00AD | 0x200B..=0x200F | 0x202A..=0x202E | 0x2060..=0x2069 | 0xFEFF | 0xE0000..=0xE007F)
    })
}

/// Renders `text` with every non-ASCII-printable character as `\u{...}`.
fn escaped(text: &str) -> String {
    text.chars()
        .map(|c| {
            if c.is_ascii_graphic() || c == ' ' {
                c.to_string()
            } else {
                format!("\\u{{{:04X}}}", c as u32)
            }
        })
        .collect()
}

fn severity_label(severity: Severity) -> &'static str {
    match severity {
        Severity::Critical => "CRITICAL",
        Severity::High => "HIGH",
        Severity::Medium => "MEDIUM",
        Severity::Low => "LOW",
    }
}

/// Renders the whole catalogue. Deterministic: categories keep their declared
/// order, patterns are sorted by id, so regeneration produces a stable diff.
pub fn render(categories: &[PatternCategory]) -> String {
    let mut out = String::new();
    let total: usize = categories.iter().map(|c| c.patterns.len()).sum();

    out.push_str("# Pattern Catalogue\n\n");
    out.push_str(GENERATED_MARKER);
    out.push_str("\n\nEvery detection pattern this scanner ships, with a worked example of what it\ncatches. Regenerate with:\n\n```bash\ncargo run --release -- rules --format markdown > docs/PATTERN-CATALOGUE.md\n```\n\n");
    out.push_str("Each example is verified in CI: `tests/pattern_example_test.rs` asserts that\nevery `example` matches its own pattern and that no `counter_example` does. An\nentry here cannot drift from the regex beside it without failing the build.\n\n");
    out.push_str("> **Detection is pattern-based and incomplete.** These are literal and\n> near-literal phrasings, not semantic understanding. A payload phrased around\n> them will not be caught. Known gaps are tracked in\n> [`DETECTION-BACKLOG.md`](DETECTION-BACKLOG.md).\n\n");

    out.push_str(&format!(
        "## Summary\n\n**{total} patterns** across {} categories.\n\n",
        categories.len()
    ));
    out.push_str("| Category | Patterns | Default severity |\n|---|---|---|\n");
    for c in categories {
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            c.category,
            c.patterns.len(),
            severity_label(c.default_severity)
        ));
    }

    let mut counts = [0usize; 4];
    for c in categories {
        for p in &c.patterns {
            match p.severity.unwrap_or(c.default_severity) {
                Severity::Critical => counts[0] += 1,
                Severity::High => counts[1] += 1,
                Severity::Medium => counts[2] += 1,
                Severity::Low => counts[3] += 1,
            }
        }
    }
    out.push_str(&format!(
        "\n| CRITICAL | HIGH | MEDIUM | LOW |\n|---|---|---|---|\n| {} | {} | {} | {} |\n",
        counts[0], counts[1], counts[2], counts[3]
    ));

    for category in categories {
        out.push_str(&format!("\n---\n\n## {}\n\n", category.category));
        let mut patterns: Vec<_> = category.patterns.iter().collect();
        patterns.sort_by(|a, b| a.id.cmp(&b.id));

        for p in patterns {
            let severity = p.severity.unwrap_or(category.default_severity);
            // The name is an identifier, and several of them are themselves payload
            // phrases (`ignore-previous-instructions`, `dan-mode`). A code span is
            // the correct formatting for an identifier and also keeps this
            // document from tripping the scanner it documents.
            out.push_str(&format!("### {} — `{}`\n\n", p.id, p.name));
            out.push_str(&format!("**{}**", severity_label(severity)));
            if p.severity.is_none() {
                out.push_str(" *(category default)*");
            }
            if !p.tags.is_empty() {
                out.push_str(&format!(" · `{}`", p.tags.join("` `")));
            }
            let mut flags = Vec::new();
            if p.case_sensitive == Some(true) {
                flags.push("case-sensitive");
            }
            if p.raw_only == Some(true) {
                flags.push("raw-only (skips the normalized pass)");
            }
            if !flags.is_empty() {
                out.push_str(&format!(" · {}", flags.join(", ")));
            }
            out.push_str("\n\n");

            if !p.description.is_empty() {
                out.push_str(&format!("{}\n\n", p.description));
            }

            if let Some(example) = p.example.as_deref() {
                out.push_str("Catches:\n\n```text\n");
                out.push_str(example);
                out.push_str("\n```\n\n");
                if has_invisible(example) {
                    out.push_str(&format!(
                        "The characters that matter here are invisible; escaped, that reads `{}`.\n\n",
                        escaped(example)
                    ));
                }
            }

            if let Some(counter) = p.counter_example.as_deref() {
                out.push_str("Does **not** catch:\n\n```text\n");
                out.push_str(counter);
                out.push_str("\n```\n\n");
            }

            if !p.remediation.is_empty() {
                out.push_str(&format!("**Fix:** {}\n\n", p.remediation));
            }

            out.push_str(&format!(
                "<details><summary>Regex</summary>\n\n```regex\n{}\n```\n\n</details>\n\n",
                p.pattern
            ));
        }
    }

    out.push_str("---\n\nSee [`PATTERNS.md`](../PATTERNS.md) to contribute a pattern, and\n[`DETECTION-BACKLOG.md`](DETECTION-BACKLOG.md) for what is deliberately not covered yet.\n");
    out
}
